$ErrorActionPreference = "Stop"
. "$PSScriptRoot\TestHelpers.ps1"

$source = Get-Content -LiteralPath "$PSScriptRoot\..\scripts\oss-mount-gui.ps1" -Raw
$cmdLauncher = Get-Content -LiteralPath "$PSScriptRoot\..\scripts\start-oss-mount-gui.cmd" -Raw
$vbsLauncherPath = "$PSScriptRoot\..\scripts\start-oss-mount-gui.vbs"
$vbsLauncher = Get-Content -LiteralPath $vbsLauncherPath -Raw
Assert-True ($source.Contains("OssMount.Core.ps1")) "GUI loads the shared core"
Assert-True ($source.Contains("OssMount.Tasks.ps1")) "GUI loads the shared task service"
Assert-True ($source.Contains("OssMount.Removal.ps1")) "GUI loads the shared removal service"
Assert-True ($source.Contains("OssMount.Localization.ps1")) "GUI loads localization"
Assert-True ($source.Contains("NavConnection")) "GUI has the connection navigation page"
Assert-True ($source.Contains("NavSettings")) "GUI has the settings navigation page"
Assert-True ($source.Contains("NavActivity")) "GUI has the activity navigation page"
Assert-True ($source.Contains("Save-CrossCloudConnectionState")) "GUI persists non-sensitive connection state"
Assert-True ($source.Contains("New-AlibabaOssRemoteDefinition")) "GUI uses the Alibaba provider contract"
Assert-True ($source.Contains("Get-CrossCloudMountArguments")) "GUI uses shared mount arguments"
Assert-True ($source.Contains("Set-CrossCloudScheduledTasks")) "GUI uses shared scheduled task setup"
Assert-True ($source.Contains("Remove-CrossCloudConnection")) "GUI uses shared removal flow"
Assert-True (-not $source.Contains("--no-modtime")) "GUI does not disable modification times"
Assert-True ($source -notmatch '(?i)taskkill\s+/IM\s+rclone') "GUI does not terminate every rclone process"
Assert-True ($source -notmatch '(?i)rclone\s+(delete|purge)') "GUI never deletes cloud objects"
Assert-True ($source.Contains("Apply-Language")) "GUI exposes runtime language switching"
Assert-True ($source.Contains("Get-LanguageSwitchText")) "GUI renders the language switch without locale-sensitive literals"
Assert-True ($source.Contains('([char]0x4E2D).ToString() + ([char]0x6587).ToString()')) "GUI builds the Chinese language label from Unicode code points"
Assert-True (-not $source.Contains('"中文"')) "GUI avoids hard-coded Chinese literals that can mojibake under Windows PowerShell 5.1"
Assert-True ($source.Contains("Refresh-LocalizedChoices")) "GUI refreshes localized choice text"
Assert-True ($source.Contains("Get-SelectedRegionId")) "GUI reads region IDs through an explicit selection map"
Assert-True ($source.Contains("Set-SelectedRegionId")) "GUI restores region selection through an explicit selection map"
Assert-True ($source.Contains('$script:RegionChoice.Items.Add([string]$region.Display)')) "GUI displays only localized region names"
Assert-True (-not $source.Contains('RegionChoice.DataSource')) "GUI avoids PowerShell 5.1 ComboBox object binding for regions"
Assert-True (-not $source.Contains('RegionChoice.SelectedValue')) "GUI avoids passing ComboBox objects as region IDs"
Assert-True ($source.Contains('Add_SelectedIndexChanged({ Update-Endpoint })')) "GUI updates endpoints when the region index changes"
Assert-True ($source.Contains("Set-CrossCloudMountPaused")) "GUI manual stop pauses automatic recovery until sign-in"
Assert-True ($source.Contains("Clear-CrossCloudMountPaused")) "GUI reconnect clears the manual stop marker"
Assert-True ($source.Contains("MessageBoxButtons")) "GUI uses typed confirmation dialog options"
Assert-True ($source.Contains("ShowSecretCheck")) "GUI has an accessible Secret visibility control"
Assert-True ($source.Contains("ActivityFilter")) "GUI exposes activity type filters"
Assert-True ($source.Contains("Set-OperationBusy")) "GUI centralizes busy button state"
Assert-True ($source.Contains("Test-OssAccess")) "GUI shares the OSS access test between test and connect flows"
Assert-True ($source -match '(?s)function Connect-CloudDrive.*?Test-OssAccess') "GUI verifies OSS access before mounting"
Assert-True ($source.Contains('AutoScaleMode = "Dpi"')) "GUI enables DPI-aware scaling"
Assert-True ($source.Contains('MinimumSize = New-Object Drawing.Size(820, 560)')) "GUI supports the specified minimum window size"
Assert-True ($source.Contains('FormBorderStyle = "Sizable"')) "GUI can resize within the minimum size"
Assert-True ($source.Contains("CacheRecommendationCustom")) "GUI provides guidance for custom cache sizes"
Assert-True ($source.Contains('Get-Service -Name "WinFsp.Launcher"')) "GUI detects the WinFsp service installation"
Assert-True ($source.Contains("Set-ResponsiveLayout")) "GUI recalculates layout after resizing"
Assert-True ($source.Contains('($width - $leftMargin - $rightMargin - $columnGap) / 2')) "GUI divides available width into non-overlapping columns"
Assert-True ($source.Contains('ClientSize = New-Object Drawing.Size(980, 700)')) "GUI opens with enough vertical space for the settings page"
Assert-True ($source.Contains('AutoScrollMinSize = New-Object Drawing.Size(0, 720)')) "Settings page scrolls vertically at the minimum window height"
Assert-True ($source.Contains('$script:CacheAdviceLabel.Location = New-UiPoint -X $leftMargin -Y 558')) "Cache guidance uses a dedicated row"
Assert-True ($source -match 'New-Object\s+-TypeName\s+Drawing\.Point\s+-ArgumentList') "Responsive point coordinates use explicit constructor arguments"
Assert-True ($source.Contains('SensitiveValues @($Values.AccessKeyId, $Values.AccessKeySecret)')) "GUI redacts both AccessKey fields from process output"
Assert-True (Test-Path -LiteralPath $vbsLauncherPath) "GUI includes a no-console double-click launcher"
Assert-True ($cmdLauncher.Contains('wscript.exe')) "CMD launcher delegates to the no-console launcher"
Assert-True ($vbsLauncher.Contains('-WindowStyle Hidden')) "No-console launcher hides the PowerShell host window"
Assert-True ($vbsLauncher.Contains('-STA')) "No-console launcher starts WinForms in STA mode"

Complete-TestFile
